# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os
import sphinx
import datetime

# -- Project information -----------------------------------------------------

project = 'OPC UA Modbus Gateway'
version = "1.0"
copyright = '2025, ASNeG'
author = 'Kai Huebl'

html_context = {
    'docs_scope': 'external',
    'cover_logo_title': '',
    'cover_meta_data': 'OpcUaModbusGateway',
    'cover_footer': f'Build: {datetime.datetime.now().strftime("%d.%m.%Y")}<br>'
                    f'Maintained by Kai Huebl AG</a>',
}

# -- RST Prolog -------------------------------------------------------------

# Defines new global rst roles and links them with the css classes from the
# custom.css file.
# To use a rst role like: :topic:`Zweck`

rst_prolog = """
.. role:: bolditalic
  :class: bolditalic

.. role:: topic
  :class: topic

.. role:: todo
  :class: todo
"""

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_simplepdf',
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinx.ext.extlinks',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.imgmath',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
#html_theme = 'bizstyle'
#html_theme = 'pyramid'
html_theme = 'sphinx_rtd_theme'

html_static_path = ['_static']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ["custom.css"]

# -- Options simple pdf ------------------------------------------------

# This Sphinx extension provides an easy way to build beautiful PDFs based on CSS rules.
# https://sphinx-simplepdf.readthedocs.io/en/latest/

simplepdf_vars = {
    'primary': '#003c6d',
    'primary-opaque': 'rgba(0, 60, 109, .5)',
    'cover-overlay': 'rgba(35, 106, 185, 0.5)',
    'cover-bg': 'url(industry.png) no-repeat center',
    'cover': '#ffffff',
    'white': '#ffffff',
    'links': '#1a961a',
    'top-left-content': 'counter(page)',
    'bottom-left-content': 'counter(page)',
    'bottom-right-content': 'string(heading)'
}


